# Generated by Django 5.2.6 on 2025-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.IntegerField()),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField()),
                ('brokers', models.TextField()),
                ('fc_inicio', models.IntegerField()),
                ('fc_final', models.IntegerField()),
            ],
            options={
                'db_table': 'campaigns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignsEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'campaigns_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.IntegerField()),
                ('id_domicilio', models.PositiveIntegerField()),
                ('id_ocupacion', models.IntegerField()),
                ('id_estado_civil', models.IntegerField()),
                ('ci', models.BigIntegerField()),
                ('nombre1', models.CharField(max_length=32)),
                ('nombre2', models.CharField(max_length=32)),
                ('apellido1', models.CharField(max_length=32)),
                ('apellido2', models.CharField(max_length=32)),
                ('fc_nacimiento', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('zurdo', models.CharField(max_length=1)),
                ('id_tel_fijo1', models.IntegerField()),
                ('id_tel_fijo2', models.IntegerField()),
                ('id_tel_movil1', models.IntegerField()),
                ('id_tel_movil2', models.IntegerField()),
                ('email', models.TextField()),
                ('id_userinsert', models.IntegerField()),
                ('id_fuente_dato', models.IntegerField()),
                ('se_queda', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('lastupdate', models.DateTimeField()),
                ('mascota', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactosEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'contactos_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gestiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('id_campaign', models.IntegerField()),
                ('id_broker', models.IntegerField()),
                ('id_contacto', models.IntegerField()),
                ('id_resultado', models.IntegerField()),
                ('notas', models.TextField()),
                ('timestamp', models.CharField(max_length=14)),
                ('id_tel_fijo1', models.IntegerField()),
                ('lastupdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'gestiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionesResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'gestiones_resultado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionesTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'gestiones_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('numero', models.PositiveBigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'telefonos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('id_estado', models.IntegerField()),
                ('id_grupo', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
                ('ci', models.IntegerField()),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('usuario', models.CharField(max_length=32)),
                ('password', models.TextField()),
                ('id_tipo_escala', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'users_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'users_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'users_grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'users_tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contactabilidad', models.FloatField()),
                ('penetracion_bruta', models.FloatField()),
                ('penetracion_neta', models.FloatField()),
                ('filtros', models.JSONField()),
            ],
        ),
    ]
